services:
  agent-issuer:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: start --arg-file demo.yml --label agent-issuer -e http://agent-issuer:3000 --log-level info --webhook-url=http://issuer:3008/webhooks
    ports:
      - 3001:3001

  agent-holder:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: start --arg-file demo.yml --label agent-holder -e http://agent-holder:3000 --log-level info --webhook-url=http://holder:3008/webhooks

  issuer:
    build:
      context: ..
      dockerfile: docker/Dockerfile.issuer
    stdin_open: true
    tty: true
    ports:
      - 3008
    depends_on:
      - agent-issuer

  holder:
    build:
      context: ..
      dockerfile: docker/Dockerfile.holder
    stdin_open: true
    tty: true
    ports:
      - 3008
    depends_on:
      - agent-holder

  tails:
    image: ghcr.io/bcgov/tails-server:latest
    platform: linux/amd64
    ports:
      - 6543:6543
    command: >
      tails-server
      --host 0.0.0.0
      --port 6543
      --storage-path /tmp/tails-files
      --log-level INFO
