label: basicmessage_storage

# Admin
admin: [ 0.0.0.0, 3001 ]
admin-insecure-mode: true
# admin-api-key: change-me

# Transport
inbound-transport:
  - [ http, 0.0.0.0, 3000 ]
outbound-transport: http
endpoint:
  - http://host.docker.internal:3000

# plugins
plugin:
  - oid4vci.v1_0

#config
genesis-url: https://indy.igrant.io/genesis

log-level: info

auto-accept-invites: true
auto-respond-messages: true