label: bob

auto-provision: true

admin: [0.0.0.0, 4001]
admin-insecure-mode: true

inbound-transport:
  - [http, 0.0.0.0, 4000]

outbound-transport: http
endpoint:
  - http://localhost:4000

plugin:
  - issue_credential.v1_0

genesis-url: http://test.bcovrin.vonx.io/genesis

log-level: info

wallet-name: bob_wallet
wallet-key: bob_wallet_key

auto-accept-invites: true
auto-respond-messages: true
