[tool.poetry]
name = "redis-inbound-outbound-services"
version = "0.1.0"
description = "ACA-Py Redis HTTP and WS inbound/outbound services"
authors = ["Shaanjot Gill <gill.shaanjots@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
redis = "^5.2.1"
aiohttp = "^3.12.6"
fastapi-slim = "^0.115.14"
uvicorn = "^0.35.0"
nest-asyncio = "^1.5.5"
pydantic = "^2.11.9"

[tool.poetry.group.dev.dependencies]
black = "~24.8.0"
flake8 = "^3.9.1"
pre-commit = "^2.12.1"
pytest = "^8.3.5"
pytest-cov = "^5.0.0"
pytest-asyncio = "^1.1.0"
rope = "^1.13.0"

[build-system]
requires = ["setuptools", "poetry-core>=2.1"]
build-backend = "poetry.core.masonry.api"
