[tool.poetry]
name = "redis-inbound-outbound-services"
version = "0.1.0"
description = "ACA-Py Redis HTTP and WS inbound/outbound services"
authors = ["Shaanjot Gill <gill.shaanjots@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.12"
redis = "^5.2.0"
aiohttp = "^3.10.5"
fastapi-slim = "^0.115.5"
uvicorn = "^0.32.0"
nest-asyncio = "^1.5.5"
pydantic = "^2.7.0"

[tool.poetry.dev-dependencies]
black = "~24.8.0"
flake8 = "^3.9.1"
pre-commit = "^2.12.1"
pytest = "^8.3.1"
pydantic = "~2.7.0"
pytest-cov = "^5.0.0"
pytest-asyncio = "^0.24.0"
rope = "^1.13.0"

[build-system]
requires = ["setuptools", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
