auto-provision: true
label: plugins

inbound-transport:
   - [http, 0.0.0.0, 9060]

outbound-transport: http

emit-new-didcomm-prefix: true
wallet-type: askar
wallet-storage-type: default

admin-insecure-mode: true

admin: [0.0.0.0, 9061]

endpoint: http://host.docker.internal:9060

genesis-url: https://indy.igrant.io/genesis

# Connections
debug-connections: true
auto-accept-invites: true
auto-accept-requests: true
auto-ping-connection: true
auto-respond-messages: true

# multitenant
multitenant: true
multitenant-admin: true
jwt-secret: changeme

log-level: info

# plugins
plugin:
  - basicmessage_storage.v1_0