version: '3'
#***************************************************************
# integration level test agents                                *
#***************************************************************

services:
  holder:
    image: plugin-image
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: start --arg-file integration.yml --label holder -e http://holder:3000 --log-level info

  issuer:
    image: plugin-image
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: start --arg-file integration.yml --label issuer -e http://issuer:3000 --log-level info

  tails:
    image: ghcr.io/bcgov/tails-server:latest
    platform: linux/amd64
    ports:
      - 6543:6543
    command: >
      tails-server
      --host 0.0.0.0
      --port 6543
      --storage-path /tmp/tails-files
      --log-level INFO

  tests:
      container_name: juggernaut
      build:
        context: .
        dockerfile: Dockerfile.test.runner
      environment:
        - WAIT_BEFORE=3
        - WAIT_HOSTS=holder:3000,issuer:3000
        - WAIT_TIMEOUT=60
        - WAIT_SLEEP_INTERVAL=1
        - WAIT_HOST_CONNECT_TIMEOUT=30
      depends_on:
        - holder
        - issuer
        - tails
