version: '3'
services:
  #*************************************************************
  # zookeeper:                                                 *
  #*************************************************************
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  #*************************************************************
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #*************************************************************
  restproxy:
    image: confluentinc/cp-kafka-rest
    restart: always
    depends_on:
      - zookeeper
      - kafka
    hostname: restproxy
    container_name: restproxy
    environment:
      KAFKA_REST_HOST_NAME: restproxy
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_REST_LISTENERS: http://0.0.0.0:8086

  relay:
    image: http-kafka-relay
    build:
      context: ../http_kafka_relay
    ports:
      - 3000:80
    environment:
      - KAFKA_BOOTSTRAP=kafka
      - INBOUND_TOPIC=acapy-inbound-message
      - WAIT_BEFORE_HOSTS=5
      - WAIT_HOSTS=zookeeper:2181,kafka:9092
      - WAIT_HOSTS_TIMEOUT=120
      - WAIT_SLEEP_INTERVAL=1
      - WAIT_HOST_CONNECT_TIMEOUT=60
    depends_on:
      - kafka

  #*************************************************************
  # acapy-kafka_queue: aca-py that produces kafka events.      *
  #*************************************************************
  acapy-kafka-queue:
    image: acapy-kafka-queue
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - kafka
      - zookeeper
      - restproxy
      - relay
    command: start -it kafka_queue.inbound kafka 0 -oq kafka_queue.outbound.KafkaOutboundQueue -e http://relay:80 --no-ledger --admin 0.0.0.0 3001 --admin-insecure-mode --plugin kafka_queue --log-level debug
    environment:
      - WAIT_BEFORE_HOSTS=5
      - WAIT_HOSTS=zookeeper:2181,kafka:9092,restproxy:8086,relay:80
      - WAIT_HOSTS_TIMEOUT=120
      - WAIT_SLEEP_INTERVAL=1
      - WAIT_HOST_CONNECT_TIMEOUT=60


  #*************************************************************
  # tester: drives tests in a                                  *
  # "Juggernaut" fashion!                                      *
  #*************************************************************

  tests:
      container_name: juggernaut
      build:
        context: .
        dockerfile: Dockerfile.test.runner
      environment:
        - WAIT_BEFORE_HOSTS=6
        - WAIT_HOSTS=zookeeper:2181, kafka:9092, restproxy:8086, acapy-kafka-queue:3001
        - WAIT_HOSTS_TIMEOUT=120
        - WAIT_SLEEP_INTERVAL=1
        - WAIT_HOST_CONNECT_TIMEOUT=60
        - AGENT_HOST=acapy-kafka-queue
        - AGENT_PORT=3000
        - AGENT_BACKCHANNEL_PORT=3001
        - SUITE_HOST=tests
        - SUITE_PORT=3002
      depends_on:
        - zookeeper
        - kafka
        - acapy-kafka-queue
        - kafka-visuals

  kafka-visuals:
    image: kbhargava/kafka-visuals
    ports:
      - 8080:8080
    depends_on:
      - kafka
      - zookeeper
    command: zookeeper:2181 kafka:9092 DEV
