version: '3'
#***************************************************************
# integration level test agents                                *
#***************************************************************

services:
  bob:
    image: plugin-image
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3002:3001"
    command: >
      start
        --label Bob
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --endpoint http://bob:3000
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --tails-server-base-url http://tails:6543
        --genesis-url https://test.bcovrin.vonx.io/genesis
        --wallet-type askar
        --wallet-name bob
        --wallet-key insecure
        --auto-provision
        --log-level info
        --debug-webhooks
        --monitor-revocation-notification
        --plugin present_proof.v1_0
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5

  alice:
    image: plugin-image
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3001:3001"
    command: >
      start
        --label Alice
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --endpoint http://alice:3000
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --tails-server-base-url http://tails:6543
        --genesis-url https://test.bcovrin.vonx.io/genesis
        --wallet-type askar
        --wallet-name alice
        --wallet-key insecure
        --auto-provision
        --log-level info
        --debug-webhooks
        --plugin present_proof.v1_0
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5
    depends_on:
      tails:
        condition: service_started

  tails:
    image: ghcr.io/bcgov/tails-server:latest
    ports:
      - 6543:6543
    environment:
      - GENESIS_URL=https://test.bcovrin.vonx.io/genesis
    command: >
      tails-server
      --host 0.0.0.0
      --port 6543
      --storage-path /tmp/tails-files
      --log-level INFO

  tests:
      container_name: juggernaut
      build:
        context: .
        dockerfile: Dockerfile.test.runner
      environment:
        - WAIT_BEFORE=3
        - WAIT_HOSTS=bob:3000, alice:3000
        - WAIT_TIMEOUT=60
        - WAIT_SLEEP_INTERVAL=1
        - WAIT_HOST_CONNECT_TIMEOUT=30
        - ALICE=http://alice:3001
        - BOB=http://bob:3001
      depends_on:
        alice:
          condition: service_healthy
        bob:
          condition: service_healthy