version: '3'
#***************************************************************
# integration level test agents                                *
#***************************************************************

services:
  bob:
    image: plugin-image
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: start --arg-file integration.yml --label bob -e http://bob:3000 --log-level info


  tests:
      container_name: juggernaut
      build:
        context: .
        dockerfile: Dockerfile.test.runner
      environment:
        - WAIT_BEFORE_HOSTS=3
        - WAIT_HOSTS=bob:3000
        - WAIT_HOSTS_TIMEOUT=60
        - WAIT_SLEEP_INTERVAL=1
        - WAIT_HOST_CONNECT_TIMEOUT=30
      depends_on:
        - bob
