version: '3'
#***************************************************************
# integration level test agents                                *
#***************************************************************

services:
  alice:
    image: plugin-image
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3001:3001"
    environment:
      RUST_LOG: 'aries-askar::log::target=error'
    command: >
      start
        --label Alice
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --endpoint http://alice:3000
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --genesis-url http://test.bcovrin.vonx.io/genesis
        --wallet-type askar
        --wallet-name alice
        --wallet-key insecure
        --auto-provision
        --log-level debug
        --auto-accept-invites
        --plugin issue_credential.v1_0
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5

  bob:
    image: plugin-image
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3002:3001"
    environment:
      RUST_LOG: 'aries-askar::log::target=error'
    command: >
      start
        --label Bob
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --endpoint http://bob:3000
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --genesis-url http://test.bcovrin.vonx.io/genesis
        --wallet-type askar
        --wallet-name bob
        --wallet-key insecure
        --auto-provision
        --log-level info
        --monitor-revocation-notification
        --auto-accept-invites
        --plugin issue_credential.v1_0
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5

  tests:
      container_name: juggernaut
      build:
        context: .
        dockerfile: Dockerfile.test.runner
      environment:
        - WAIT_BEFORE=3
        - WAIT_HOSTS=bob:3000, alice:3000
        - WAIT_TIMEOUT=60
        - WAIT_SLEEP_INTERVAL=1
        - WAIT_HOST_CONNECT_TIMEOUT=30
      depends_on:
        - bob
        - alice