label: present_proof

auto-provision: true

admin: [0.0.0.0, 3001]
admin-insecure-mode: false
admin-api-key: change-me

inbound-transport:
  - [http, 0.0.0.0, 3000]
  - [ws, 0.0.0.0, 3002]
outbound-transport: http
endpoint:
  - http://host.docker.internal:3000

plugin:
  - present_proof.v1_0

genesis-url: http://test.bcovrin.vonx.io/genesis

log-level: info

wallet-name: present_proof_wallet
wallet-key: present_proof_wallet_key

auto-accept-invites: true
auto-respond-messages: true
