[tool.poetry]
name = "runner"
version = "0.1.0"
description = "Test runner with wrapper around AFJ using JSON-RPC"
authors = ["Daniel Bluhm <dbluhm@pm.me>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
async-selective-queue = "^0.1.0.post0"

[tool.poetry.group.dev.dependencies]
black = "^23.11.0"
ruff = "^0.1.5"

[tool.ruff]
select = ["E", "F", "C", "D"]

ignore = [
    # Google Python Doc Style
    "D203", "D204", "D213", "D215", "D400", "D401", "D404", "D406", "D407",
    "D408", "D409", "D413",
    "D202", # Allow blank line after docstring
    "D104", # Don't require docstring in public package
    # Things that we should fix, but are too much work right now
    "D417", "C901",
]

line-length = 90

[tool.ruff.per-file-ignores]
"**/{tests}/*" = ["F841", "D", "E501"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
