[tool.poetry]
name = "redis_events-tests"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^8.2.2"
pytest-asyncio = "~0.23.7"
requests = "^2.31.0"
aiohttp = "^3.9.5"
aries-cloudagent = { version = ">=0.10.3, < 1.0.0" }
fastapi-slim = "^0.111.0"
nest-asyncio = "^1.5.5"
pydantic = "^1.10.15"
redis = "^5.0.4"
uvicorn = "^0.29.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

