[tool.poetry]
name = "redis_events-tests"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^7.4.0"
pytest-asyncio = "^0.21.0"
asynctest = "^0.13.0"
requests = "^2.31.0"
aiohttp = "^3.7.4"
aries-cloudagent = { version = ">=0.10.3, < 1.0.0" }
fastapi = "^0.109.1"
nest-asyncio = "^1.5.5"
pydantic = "^1.8.2"
redis = "^4.1.4"
uvicorn = "0.16.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

