[tool.poetry]
name = "redis_events-tests"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^8.2.2"
pytest-asyncio = "~0.23.7"
requests = "^2.32.0"
aiohttp = "^3.9.5"
aries-cloudagent = { version = "~1.0.0", optional = true }
fastapi-slim = "^0.115.0"
nest-asyncio = "^1.5.5"
redis = "^5.1.1"
uvicorn = "^0.30.1"
pydantic = "^2.7.0"

[tool.poetry.dev-dependencies]

[tool.pytest.ini_options]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

