name: Pull Request
on:
  pull_request:
    types: [ready_for_review]
    branches:
      - "**"

jobs:
  integration-tests:
    name: "Integration tests"
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and install poetry
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Initialize Docker Compose
        uses: isbang/compose-action@v1.5.1
      #----------------------------------------------
      #       Run integration Tests
      #----------------------------------------------
      - name: Run integration tests
        id: integration-tests
        run: |

          # This will navigate to each subdirectory and perform integration tests
          # If we have a directory that isn't a plugin then it will need to skip it. Currently there is none. 

          for dir in ./*/; do
            cd $dir
            cd integration
            docker compose build
            docker compose up -d
            cd ..
          done
