name: Release

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - "**"

permissions:
  contents: write

jobs:

  checks:
    name: "Check global version"
    runs-on: ubuntu-latest
    outputs:
      current_available_version: ${{ steps.current_available_version.outputs.version }}
      current_global_version: ${{ steps.current_global_version.outputs.version }}
    defaults:
      run:
        working-directory: ./plugin_globals
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install poetry
        run: pipx install poetry
        id: setup-poetry
      
      - name: Get latest aries-cloudagent version
        id: current_available_version
        run: |
          remote_version=$(pip index versions aries-cloudagent)
          version=$(grep -oP '(?<=Available versions: ).*?(?=,)' <<< "$remote_version")
          echo "Remote version = $version"

      - name: Get global aries-cloudagent version from plugins repo
        id: current_global_version
        run: |
          lock_version=$(grep -A1 'name = "aries-cloudagent"' poetry.lock | grep -v 'name = "aries-cloudagent"')
          version=$(grep -oP '(?<=").*?(?=")' <<< "$lock_version")
          echo "Global version = $version"
      - name: Update global acapy version
        run: |
          cd .. && python repo_manager.py 3
          echo "Update global acapy version"
      - name: Create Pull Request
        run: |
          git config --global user.name 'Jamie Hale'
          git config --global user.email 'jamshale@users.noreply.github.com'
          git remote set-url --push origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/jamshale/aries-acapy-plugins
          git fetch --all
          git checkout -b release
          git add . 
          git push --set-upstream origin release
          git request-pull main release

    # git commit -m "Automated Pull Request"
    # git push --set-upstream origin main
    
    # git request-pull v1.0 https://github.com/jamshale/aries-acapy-plugins 
